project 'NYSCake_Demo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NYSCake_Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NYSCake_Demo
  pod 'NYSMC' , '~> 0.0.3'

  target 'NYSCake_DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
